# Generated by Django 5.1.3 on 2024-11-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_no', models.CharField(db_index=True, max_length=120, unique=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('min_qty_per_kg', models.PositiveIntegerField(blank=True, default=0)),
                ('max_qty_per_kg', models.PositiveIntegerField(blank=True, default=0)),
                ('verified', models.BooleanField(default=False, help_text='Is the vendor verified?')),
                ('active', models.BooleanField(default=True, help_text='Is the vendor active?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commodities', models.ManyToManyField(blank=True, related_name='vendors', to='commodities.commodity')),
            ],
        ),
    ]
