# Generated by Django 5.1.3 on 2024-11-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(default='', max_length=220),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
